name: Build MacOS dependencies

on:
  workflow_dispatch:
  release:
    types: [published]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  HIGHFIVE_VERSION: "2.4.1"
  BOOST_VERSION: "1.79.0"
  EIGEN_VERSION: "3.4.0"
  HDF5_VERSION: "1.12.2"
  LIBINT_VERSION: "2.7.1"
  GMP_VERSION: "6.2.1"

jobs:
  build:
    name: Build MacOS macosx_${{ matrix.arch[0] }} dependencies
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          # [<architecture>, <min darwin version>]
          - ["x86_64", "10.4"]
          - ["arm64", "11"]
    env:
      MACOSX_DEPLOYMENT_TARGET: ${{ matrix.arch[1] }}
      CC: "/usr/bin/clang"
      CXX: "/usr/bin/clang++"
      CXXFLAGS: "-std=c++11 -arch ${{ matrix.arch[0] }}"
      PREFIX: ${{github.workspace}}/macos_${{ matrix.arch[0] }}
      CFLAGS: "-arch ${{ matrix.arch[0] }}"
      CPPFLAGS: "-arch ${{ matrix.arch[0] }}"
      LDFLAGS: "-arch ${{ matrix.arch[0] }}"
      HOST: "${{ matrix.arch[0] }}-apple-darwin"

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3

    - name: Install dependencies
      run: pip install -e .

    - name: Python info
      run: |
        which python
        python --version

    - name: Clang info
      run: clang --version

    - name: Installed packages
      run: pip list

    - name: Create output directories
      run: |
        mkdir -p $PREFIX/lib
        mkdir -p $PREFIX/bin
        mkdir -p $PREFIX/include

    - name: Install Automake
      run: |
        brew update
        brew install automake

    - name: Install HighFive
      run: python tools/install_highfive.py $HIGHFIVE_VERSION --prefix=$PREFIX

    - name: Install Boost
      run: python tools/install_boost.py $BOOST_VERSION --prefix=$PREFIX

    - name: Install Eigen
      run: python tools/install_eigen.py $EIGEN_VERSION --prefix=$PREFIX

    - name: Install GMP
      if: matrix.arch[0] == 'arm64'
      run: |
        export CFLAGS="$CFLAGS --target=$HOST"
        python tools/install_gmp.py $GMP_VERSION --host=$HOST

    - name: Install HDF5
      run: |
        case "${{ matrix.arch[0] }}" in
          "arm64")
            export APPLY_HDF5_PATCH=1
            export ac_cv_sizeof_long_double=8
            export hdf5_cv_ldouble_to_long_special=no
            export hdf5_cv_long_to_ldouble_special=no
            export hdf5_cv_ldouble_to_llong_accurate=yes
            export hdf5_cv_llong_to_ldouble_correct=yes
            export hdf5_cv_disable_some_ldouble_conv=no
            export hdf5_cv_system_scope_threads=yes
            export hdf5_cv_printf_ll="l"
            export PATH="/tmp/native-build/bin:$PATH"
            export HOST="aarch64-apple-darwin${{ matrix.arch[1] }}"
            mkdir -p /tmp/native-build/bin
            ;;
        esac

        python tools/install_hdf5.py $HDF5_VERSION \
          --prefix=$PREFIX \
          --libdir=/usr/local/lib \
          --host=$HOST
        cp /usr/local/lib/libhdf5* $PREFIX/lib/

    - name: Install Libint
      run: |
        case "${{ matrix.arch[0] }}" in
          "arm64")
            export HOST="aarch64-apple-darwin${{ matrix.arch[1] }}" ;;
        esac

        cp -r $PREFIX/include/* /usr/local/include/
        python tools/install_libint.py $LIBINT_VERSION \
          --prefix=$PREFIX \
          --libdir=/usr/local/lib \
          --build=x86_64-apple-darwin \
          --host=$HOST \
          --target=$HOST
        cp /usr/local/lib/libint2* $PREFIX/lib/

    - name: Create archive
      run: tar -czvf $PREFIX.tar.gz macosx_x86_64

    - uses: actions/upload-artifact@v3
      with:
        name: deps
        path: macosx_*.tar.gz

  upload_wheels:
    name: Attach artifacts to release
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == 'release'
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: deps
          path: output

      - name: Attach artifacts to GitHub release
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'output/*'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
